# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        
        # Adding model 'Person'
        db.create_table('etreg_person', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('lastname', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('firstname', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('address', self.gf('django.db.models.fields.CharField')(max_length=50, null=True, blank=True)),
            ('dateofbirth', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
            ('height', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('postalcode', self.gf('django.db.models.fields.CharField')(max_length=50, null=True, blank=True)),
            ('city', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('clubmember', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('country', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('whichclub', self.gf('django.db.models.fields.CharField')(max_length=75, null=True, blank=True)),
            ('email', self.gf('django.db.models.fields.EmailField')(max_length=75, null=True, blank=True)),
            ('membnumb', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('mobilephone', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('homephone', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('fax', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('language', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('flightarrlocation', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('flightdeplocation', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('flightarrdate', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
            ('flightarrtime', self.gf('django.db.models.fields.CharField')(max_length=5, null=True, blank=True)),
            ('flightdepdate', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
            ('flightdeptime', self.gf('django.db.models.fields.CharField')(max_length=5, null=True, blank=True)),
            ('hotel', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('hotelother', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('hotelarrdate', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
            ('hoteldepdate', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
            ('youngtall', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('withparents', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('parentsname', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('parentsmobile', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('guardiansname', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('guardiansmobile', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('dietvegetarian', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('dietglutenfree', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('dietdiabetic', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('dietlowlactose', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('assistance', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('assistancespecify', self.gf('django.db.models.fields.CharField')(max_length=140, null=True, blank=True)),
            ('specialneeds', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('specialneedsspecify', self.gf('django.db.models.fields.CharField')(max_length=140, null=True, blank=True)),
            ('prsuarrival', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prsu1welcome', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prsusetting', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('prmonokia', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prmotampere', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prmo2welcome', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prtuboard', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prtulunch', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prtuadvpark', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prtuboat', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prwehelsinki', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prwesuomenlinna', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prwefree', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prthujuhannus', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prfrisaunapis', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prfrisaunaros', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prsatgala', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('prsugoodbye', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('yearlyfee', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('nontallclub', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('added', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, null=True, blank=True)),
            ('updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, null=True, blank=True)),
            ('ip_address', self.gf('django.db.models.fields.CharField')(max_length=15, null=True, blank=True)),
        ))
        db.send_create_signal('etreg', ['Person'])


    def backwards(self, orm):
        
        # Deleting model 'Person'
        db.delete_table('etreg_person')


    models = {
        'etreg.person': {
            'Meta': {'ordering': "['-lastname']", 'object_name': 'Person'},
            'added': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'null': 'True', 'blank': 'True'}),
            'address': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'assistance': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'assistancespecify': ('django.db.models.fields.CharField', [], {'max_length': '140', 'null': 'True', 'blank': 'True'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'clubmember': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'dateofbirth': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'dietdiabetic': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'dietglutenfree': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'dietlowlactose': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'dietvegetarian': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'null': 'True', 'blank': 'True'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'firstname': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'flightarrdate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'flightarrlocation': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'flightarrtime': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'flightdepdate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'flightdeplocation': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'flightdeptime': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'guardiansmobile': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'guardiansname': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'height': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'homephone': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'hotel': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'hotelarrdate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'hoteldepdate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'hotelother': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ip_address': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'language': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'lastname': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'membnumb': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'mobilephone': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'nontallclub': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'parentsmobile': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'parentsname': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'postalcode': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'prfrisaunapis': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prfrisaunaros': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prmo2welcome': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prmonokia': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prmotampere': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prsatgala': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prsu1welcome': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prsuarrival': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prsugoodbye': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prsusetting': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'prthujuhannus': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prtuadvpark': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prtuboard': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prtuboat': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prtulunch': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prwefree': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prwehelsinki': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prwesuomenlinna': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'specialneeds': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'specialneedsspecify': ('django.db.models.fields.CharField', [], {'max_length': '140', 'null': 'True', 'blank': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'null': 'True', 'blank': 'True'}),
            'whichclub': ('django.db.models.fields.CharField', [], {'max_length': '75', 'null': 'True', 'blank': 'True'}),
            'withparents': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'yearlyfee': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'youngtall': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        }
    }

    complete_apps = ['etreg']
